### PR TITLE
implement `runv delete`

### PR DESCRIPTION
**Pull request by YaoZengzeng**
just a simple wrapper of runv kill container-id KILL

Signed-off-by: Yao Zengzeng yaozengzeng@zju.edu.cn

### CODE REVIEW

**Comment by Crazykev** [comment]
Will it fail if exec `runv delete` after `runv kill` ?

**Comment by YaoZengzeng** [comment]
@Crazykev In fact, we can't distinguish a container being killed before and a container that never exist.
(1)、Now runv is stateless actually, the container is running or none.After kill, it just exited.
(2)、There in no api of deleting in containerd.So we can just do like this to work around.
Any good suggestions?

**Comment by Crazykev** [comment]
AFAK, for a long term, we need to follow https://github.com/opencontainers/runtime-spec/pull/513 when it land. And in runv, maybe it's more easy to figure out what is the proper way to define `delete` after we seprerate `create` and `start`.  
And if this is only a workaround for ocid integration for now, that we need a `delete`. At least we need to gurantee `delete` after `kill` will not fail, that is why I would ask that.

**Comment by gao-feng** [comment]
deleting container is  needed, please consider to implement it in containerd.

**Comment by laijs** [comment]
@YaoZengzeng  @Crazykev runv cli is being improved continuously and had just been refactored at #537 .

Moreover, `runv delete` was also implemented in #537. Feel free to test ti and give any possible feedback.

Thank you for your contribution.

**Pull request closed without merging**
