### PR TITLE
introduce api.Process

### PR DESCRIPTION
**Pull request by gao-feng**
Signed-off-by: Gao feng <omarapazanadi@gmail.com>

### CODE REVIEW

**Comment by laijs** [comment]
there is ContainerDescription in the runv/api/, should this hypervisor.Process be moved to runv/api/ ? CC @gnawux for whom create runv/api/

**Comment by gnawux** [comment]
I'd like to see it in `runv/api/`

**Comment by gao-feng** [comment]
@laijs @gnawux please review

**Comment by laijs** [comment]
should it be defined in the proto file?

**Pull request merged**
