### PR TITLE
improve docs about vbox operations

### PR DESCRIPTION
**Pull request by allencloud**
improve docs about vbox operations a little bit.

Signed-off-by: Allen Sun <shlallen1990@gmail.com>

### CODE REVIEW

**Comment by laijs** [comment]
The vbox driver has actually been removed.

**Comment by allencloud** [comment]
Thanks a lot for your feedback. @laijs 
So in another word, we could remove the docs or do some similar ways, right?

**Comment by gao-feng** [comment]
https://github.com/hyperhq/runv/pull/612

**Comment by allencloud** [comment]
Thanks @gao-feng as well for this.

**Pull request closed without merging**
