### PR TITLE
use APIVersion to wait for vm starting

### PR DESCRIPTION
**Pull request by gao-feng**
Change Launch function of vm as private function

Signed-off-by: Gao feng <omarapazanadi@gmail.com>

### CODE REVIEW

**Comment by laijs** [comment]
it is better to remove the waitStarted argument from GetVm(). the call sites who use waitStarted=true could use hyperstart API instead. (example: call the vm.GetHyperstartAPIVersion() instead). and some call sites who use waitStarted=true should be converted to who uses waitStarted=false.

alternative: call hyperstart API instead of WaitRespond in GetVm().

what do you think ?

**Comment by gao-feng** [comment]
Will update this

**Comment by gao-feng** [comment]
@laijs updated

**Comment by laijs** [comment]
LGTM

**Pull request merged**
