### PR TITLE
update network_darwin.go network_unsupported.go

### PR DESCRIPTION
**Pull request by laijs**
Signed-off-by: Lai Jiangshan <jiangshanlai@gmail.com>

### CODE REVIEW

**Comment by carmark** [comment]
The network on darwin should be unsupported, so shall we delete `network_darwin.go` file and modify `network_unsupported.go` file to make it work on darwin system?

**Comment by laijs** [comment]
It is orthogonal to the pr.

**Comment by gao-feng** [comment]
LGTM

**Comment by carmark** [comment]
@laijs  

OK, LGTM

**Pull request merged**
