### PR TITLE
rename detatch to detach

### PR DESCRIPTION
**Pull request by gao-feng**
Signed-off-by: Gao feng <omarapazanadi@gmail.com>

### CODE REVIEW

**Comment by gao-feng** [comment]
@carmark yes, it's good. but I don't know if golang or something will do spell check for us.

**Comment by carmark** [comment]
@gao-feng I don't think golang will do the spell check for us, we should do it by ourselves.

**Comment by gao-feng** [comment]
ok, that's another patch, please review this one.

**Comment by carmark** [comment]
LGTM

**Pull request merged**
