### PR TITLE
fix xen driver compile issue

### PR DESCRIPTION
**Pull request by Crazykev**
Ref: #481
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

### CODE REVIEW

**Comment by gnawux** [comment]
great, thank you @Crazykev

**Comment by Crazykev** [comment]
@gnawux I introduced this month ago... sorry for that

**Comment by gnawux** [comment]
I found the building failure when package 0.8, and have not done further investigation on it yet. ref hyperhq/hyperd#591

**Comment by Crazykev** [comment]
Oh, I see. We did not include xen in CI, #474 will fix this.
```
	runv  0.8.0
	build OS:   linux-gnu
	prefix:	    /usr/local
	has go:     yes
	with xen:   no
	with libvirt: yes
	has virtualbox: no
```

**Comment by gnawux** [comment]
I think neither hykins nor travis support xen hvm mode.

**Pull request merged**
