### PR TITLE
if the container's init process exit, clean up all other processes

### PR DESCRIPTION
**Pull request by YaoZengzeng**
fix issue #373 
Signed-off-by: Yao Zengzeng yaozengzeng@zju.edu.cn

### CODE REVIEW

**Comment by laijs** [comment]
what if the container's init process exit by itself?
have you try docker of containerd in this case? we following them.

**Comment by wrouesnel** [comment]
If the docker container's init exits, docker's behavior is to kill the rest of the container's processes.

I've been running with this patch for a while and it seems to work okay.

**Comment by laijs** [comment]
other processes will be killed in hyperstart(https://github.com/hyperhq/hyperstart/pull/96), the runv will receive the finished event, and cleanup the processes. Is this pr really needed?

**Comment by laijs** [comment]
the hyperstart does it

**Pull request closed without merging**
